### ISSUE TITLE
Installation results in an unbootable Windows 98 SE guest (VMware Workstation 17)

### ISSUE THREAD

**Issue by NTxC** [JHRobotics/softgpu#11]
I set up a fresh Windows 98 SE (Polish) virtual machine in VMware Workstation 17.0.2. I installed VMware Tools. Then, I installed softgpu v0.4.2023.11-alpha. After rebooting, I was presented with the following error on bootup:

![Screenshot of the error](https://github.com/JHRobotics/softgpu/assets/25325789/4f784aa8-7346-4cae-9faa-8a4bb6bd0853)

The English version of this specific error is:
"EMM386 - Unrecoverable privileged operation error # ?2 - Disable EMM386 and continue (K) or reboot (U)?"
Pressing K, U, Enter or other keys else doesn't do anything.

The VM settings are as follows:
![VM settings](https://github.com/JHRobotics/softgpu/assets/25325789/c69eaaef-5227-4770-9cca-e1e021c84cc4)

**Comment by Gogo268** [comment]
actual fix is to comment out SIMD95.COM loader from autoexec.bat
