### ISSUE TITLE
3DMark 99 can't detect DirectX

### ISSUE THREAD

**Issue by insertsurnamehere** [JHRobotics/softgpu#2]
First of all, i would like to thank you for this impressive project.

After creating a vm in Virtualbox, and installing the driver, i tried to run 3dmark99, but it seem to not detect direct x, even though in the setup it is recognized.

![direct x not detected](https://user-images.githubusercontent.com/42697039/234919447-7a820cb0-69fd-435f-8da0-3118c4026949.png)

Dxdiag works, it also completes the rotating cube test.
This Happens with every accelerator Virtualbox has, and Vmware too (dont remember if i ever tested qemu, but it was giving me some problems), maybe ill' try to see what's going on with dependency walker at a later time.

**Comment by insertsurnamehere** [comment]
Forgot to mention: i am running Virtualbox 6.1 on Linux Mint 21.1, on a Ryzen 3700X cpu

**Comment by JHRobotics** [comment]
Hello, 3DMark99 has known issue with DX detection – I don’t know if it is problem with DX9 or 3D Mark simply doesn’t like my replacement of `ddraw.dll` – here is the issue and workaround: https://appdb.winehq.org/objectManager.php?sClass=version&iId=6776&bShowAll=true

Workaround: download collection of 3D Mark patchers from here: https://www.vogons.org/viewtopic.php?p=641489#p641489 – you need only “3dmark.exe” and replace original file. After it you should be able to test your virtual GPU performance :-)

**Comment by insertsurnamehere** [comment]
Oh wow, now it works really well, thanks! :)
Since it seems to be an issue not specific to softgpu, can i close the issue?

**Comment by kjliew** [comment]
@JHRobotics  You can also change the DLL version reporting in `version.rc` of DDRAW.DLL to match the final DirectX runtime on Windows 98 SE. This relieves the need to patch 3DMark EXE and has the benchmark run in pristine condition.

Here's what I use
```
#define WINE_FILEVERSION 4,09,00,0904
#define WINE_FILEVERSION_STR "4.09.00.0904"
#define WINE_PRODUCTVERSION 4,09,00,0904
#define WINE_PRODUCTVERSION_STR "4.09.00.0904"
```
