### ISSUE TITLE
Divide error QEMU 7.2.0 SoftGPU VMware SVGA on Win95

### ISSUE THREAD

**Issue by CE1CECL** [JHRobotics/softgpu#21]
![image](https://github.com/JHRobotics/softgpu/assets/52040854/f5a9ad80-f575-4da7-bf48-bee5e66a8d11)

**Comment by CE1CECL** [comment]
FYI I fixed it with https://github.com/CE1CECL/qemu-vmvga/commit/501831a451db53b63c884fa7299b57f9c1ffd607

**Comment by Torinde** [comment]
JHRobotics/vmdisp9x/issues/2 discusses effects of 256MB VRAM on Win9x
JHRobotics/vmdisp9x/issues/3 links to patch for 512MB VRAM on Win9x

**Comment by CE1CECL** [comment]
> [JHRobotics/vmdisp9x/issues/2](https://github.com/JHRobotics/vmdisp9x/issues/2) discusses effects of 256MB VRAM on Win9x [JHRobotics/vmdisp9x/issues/3](https://github.com/JHRobotics/vmdisp9x/issues/3) links to patch for 512MB VRAM on Win9x

Actually it was crashing on 129+ VRAM on vmware tools drivers, which never happened before.
It works on VMware tools, but SoftGPU just hangs at a dos prompt when i boot, possibly need to vnc into windows 9x vm to see if its booting or not

**Comment by CE1CECL** [comment]
Does Direct3D work in SoftGPU? Or is it I won't get it in 4 color mode?
![image](https://github.com/JHRobotics/softgpu/assets/52040854/538fba30-8307-4c08-960c-d9a97d21e446)
VMware tools 32bpp: 
![image](https://github.com/JHRobotics/softgpu/assets/52040854/3adf3973-5c66-4b06-84b6-a64df0e5ed4e)
VMware tools 4bpp:
![image](https://github.com/JHRobotics/softgpu/assets/52040854/f3104839-fce7-47d5-8264-1e7520a97c26)
SoftGPU locks up windows on 32bpp for some reason. I don't know how to debug this old windows version, or the driver alone?
