### ISSUE TITLE
VirtualBox 6.1 or Windows 7 host potential regression?

### ISSUE THREAD

**Issue by angrylion7** [JHRobotics/softgpu#24]
VirtualBox v6.1.44
Host OS: Windows 7 x64, AVX2-capable Haswell CPU
My VM: Windows 98 SE, 512 MB RAM, 128 MB VRAM, AC97, 32-bit desktop color depth, AVX not enabled
With SoftGPU v0.4.2023.14-alpha: no problems, 3D acceleration available
Same VM upgraded to v0.4.2023.18-alpha: glchecker.exe sort of freezes on launch, eventually might show a blank white window without any graphics or controls. dxdiag.exe sort of freezes on launch, impossible to switch to the Display tab. 
With "Enable 3D acceleration" unchecked in VirtualBox settings: no problem, but too slow for my liking obviously.

**Comment by JHRobotics** [comment]
I confirm the bug, sorry for it :-(

I fixed it in Mesa9x project, you can apply the fix by download [mesa9x-23.1.6.33-lp-driver-98me.zip](https://github.com/JHRobotics/mesa9x/releases/download/v23.1.6.33/mesa9x-23.1.6.33-lp-driver-98me.zip), extract `vmwsgl32.dll` and copy it to `C:\WINDOWS\SYSTEM` (and overwrite old file).

I will do some more tests and tomorow I'll release full fixed SoftGPU package.
