### ISSUE TITLE
Mouse Pointer issue

### ISSUE THREAD

**Issue by EriolGaurhoth** [JHRobotics/softgpu#27]
VirtualBox v7.0.10 r158379
Host OS: Windows 11 Pro x64, Intel i7-11800H
My VM: Windows 98 SE, 512 MB RAM, 128 MB VRAM, AC97, 32-bit desktop color depth, AVX not enabled

With SoftGPU v0.4.2023.14-alpha: no issues, mouse is normal size and works perfectly in every game I've tried.

With the latest .18-alpha release, the mouse pointer is extremely tiny on the desktop and when I play any full-screen game (tested thus far with Unreal Gold and Need For Speed III: Hot Pursuit), the mouse cursor only allows me to access roughly the top 3rd of the screen and as I try to move the cursor down, the cursor disappears from the VirtualBox window, making anything in the lower 2/3 of the screen inaccessible.

It should be noted I've only tested the games in 640x480 resolution, which is generally the minimum resolution for most of these late '90s games. 

![image](https://github.com/JHRobotics/softgpu/assets/17301629/8e9a5519-073a-4f3f-8320-00c19e0061cc)

**Comment by JHRobotics** [comment]
Hi, this looks like some kind of high-DPI problem, as temporary solution, try to set Windows 98 screen colors 16bpp (in != 32bpp is HW cursor disabled). To next release I'll add some configuration option to turn off these features for these bugged situations.

**Comment by EriolGaurhoth** [comment]
Another temp workaround I found was to change the scaling to 100% (my VirtualBox scaling was at 200%).  Doing that returns the cursor to normal size relative to the guest OS, and the cursor works perfectly fine in all games, but the guest OS is now so tiny on my high-DPI monitor that it's hard to see.  But better than nothing, I can just change my host screen resolution to fix that for now.

Thanks for the great work on this project, it's amazing!

**Comment by JHRobotics** [comment]
Hi, in `v0.4.2023.19-alpha` I turned off HW cursor by default, so you can now increase scaling :-)

**Comment by EriolGaurhoth** [comment]
> Hi, in `v0.4.2023.19-alpha` I turned off HW cursor by default, so you can now increase scaling :-)

I installed it yesterday and it works perfectly, thanks!

**Comment by crazii** [comment]
Is there any way to enable HW cursor in v0.4.2023.19-alpha?
