### ISSUE TITLE
After installing a new driver in Windows 98 (VMWare Workstation Player 16.2.5), the virtual machine refuses to boot.

### ISSUE THREAD

**Issue by Burinis** [JHRobotics/softgpu#29]
After installing the new SoftGPU driver, Windows 98 installed in VMWare Workstation Player 16.2.5 now flatly refuses to boot and writes "EMM386 Unrecoverable privileged operation error #01".
https://ibb.co/tDqX1WQ
If I select B, the virtual machine will still not start, and if I select C, it will crash to the host's desktop.
Disabling CD, Floppy, network adapter, sound card, 3D acceleration and enabling Intel VT-X/EPT and AMD-V/RVI do not help.
What to do?

**Comment by Burinis** [comment]
Thanks to all! Unfortunately, I had to re-create the virtual machine and install Windows 98 into it, but during installation I did not check the "Enable SSE/AVX hack" checkbox. As it turned out, it is because of this option that Windows 98 does not boot for me.

**Comment by eddmanx** [comment]
When the issue gets resolved, please close it here so that it doesn't unnecessarily clutter the issues page.
