### ISSUE TITLE
resolution dependent directx detection and bsod problems

### ISSUE THREAD

**Issue by handlingcfg** [JHRobotics/softgpu#99]
on latest (v0.6.2024.37) version

1-
the 3dmark01 works normal on 1024 x 768 - 32bit resolution and it gives error on 1280 x 800 - 32bit resolution (maybe other resolutions too) saying it needs dirextx 8.1 or higher

2-
and another title, the half life gives bsod when resolution set to 1024 x 768 - both 16 and 32 bit
saying that 
0D special case happened at FF3A : 0000FFF      after the cinematics

if the desktop resolution set to  1280 x 800 - 32bpp it says half life requires dirextx 6 or above

3- 
age of empires 2 also gives bsod saying that 
0D special case happened at FF3A : 0000FFF 

r7 5700x 32 gb  + rx 5600 xt
wmware workstation pro 17.5.2    
windows 98 SE with 1 gb ram with cpu and ram patches
both vgpu9 and vgpu10 gives same errors

**Comment by JHRobotics** [comment]
Thanks for report. Unfortunately with using DDHAL extensively, some bugs show now. Problem is that DDDraw mode tables is (was) statically defined ([here](https://github.com/JHRobotics/vmdisp9x/blob/3edc12d83254c04554461fdbb310dd46d284c27c/dddrv.c#L46))  with only few basic modes and 1280x800 wasn't here (although this is relative common resolution). Inspiration for this driver was S3 Virge driver example from DDK98 and this card has all modes hard wired.

I currently commited changes, where mode tables are built dynamically and I'm going to do some tests and if goes well I'll release another hotfix release.

Currently you can workaround problem by deleting `C:\Windows\vmhal9x.dll` file (needs to be done soon after reboot or in safe mode).

**Comment by JHRobotics** [comment]
In [0.6.2024.38](https://github.com/JHRobotics/softgpu/releases/tag/v0.6.2024.38) this should be fixed!

**Comment by handlingcfg** [comment]
all fixed
